# Generated by Django 3.1.3 on 2022-01-31 04:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porfile',
            name='banner',
            field=models.ImageField(default='banner-pic-default.jpg', upload_to=accounts.models.user_banner_image),
        ),
    ]
