# Generated by Django 3.0.1 on 2022-01-17 19:26

from django.db import migrations, models
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique_for_month='published_on')),
                ('body', models.TextField()),
                ('image', models.ImageField(default='post-default.jpg', upload_to='')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('published_on', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFTED', 'draft'), ('PUBLISHED', 'publish')], default='DRAFTED', max_length=10)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
