# Generated by Django 3.1.3 on 2022-01-22 20:47

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220122_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
    ]
