# Generated by Django 3.1.3 on 2022-01-29 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220122_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_on',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
